export const SPLASH_ACTION = 'SPLASH_ACTION';
export const SPLASH_COMPLETE = 'SPLASH_COMPLETE';

export const SWITCH_LANG = 'SWITCH_LANG';
export const SWITCH_LANG_SUCCESS = 'SWITCH_LANG_SUCCESS';
export const SWITCH_LANG_FAILURE = 'SWITCH_LANG_FAILURE';

export const FETCH_AD = 'FETCH_AD';
export const FETCH_AD_SUCCESS = 'FETCH_AD_SUCCESS';
export const FETCH_AD_SUCCESS_REFURB = 'FETCH_AD_SUCCESS_REFURB';
export const FETCH_AD_FAILURE = 'FETCH_AD_FAILURE';

export const SKIP_AD = 'SKIP_AD';
export const SKIP_AD_SUCCESS = 'SKIP_AD_SUCCESS';
export const SKIP_AD_FAILURE = 'SKIP_AD_FAILURE';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const SHOW_NETWORK_MODAL = 'SHOW_NETWORK_MODAL';
export const HIDE_NETWORK_MODAL = 'HIDE_NETWORK_MODAL';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const REQUEST_BOOK = 'REQUEST_BOOK';
export const REQUEST_BOOK_SUCCESS = 'REQUEST_BOOK_SUCCESS';
export const REQUEST_BOOK_FAILURE = 'REQUEST_BOOK_FAILURE';

export const FETCH_BOOK_LISTS = 'FETCH_BOOK_LISTS';
export const FETCH_BOOK_LISTS_SUCCESS = 'FETCH_BOOK_LISTS_SUCCESS';
export const FETCH_BOOK_LISTS_FAILURE = 'FETCH_BOOK_LISTS_FAILURE';

export const FETCH_ENGLISH_BOOKS = 'FETCH_ENGLISH_BOOKS';
export const FETCH_ENGLISH_BOOKS_SUCCESS = 'FETCH_ENGLISH_BOOKS_SUCCESS';
export const FETCH_ENGLISH_BOOKS_FAILURE = 'FETCH_ENGLISH_BOOKS_FAILURE';

export const FETCH_ARABIC_BOOKS = 'FETCH_ARABIC_BOOKS';
export const FETCH_ARABIC_BOOKS_SUCCESS = 'FETCH_ARABIC_BOOKS_SUCCESS';
export const FETCH_ARABIC_BOOKS_FAILURE = 'FETCH_ARABIC_BOOKS_FAILURE';

export const FETCH_RELATED_BOOKS = 'FETCH_RELATED_BOOKS';
export const FETCH_RELATED_BOOKS_SUCCESS = 'FETCH_RELATED_BOOKS_SUCCESS';
export const FETCH_RELATED_BOOKS_FAILURE = 'FETCH_RELATED_BOOKS_FAILURE';

export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const FETCH_BOOKMARKS_SUCCESS = 'FETCH_BOOKMARKS_SUCCESS';
export const FETCH_BOOKMARKS_FAILURE = 'FETCH_BOOKMARKS_FAILURE';

export const FETCH_BOOKCLUBS = 'FETCH_BOOKCLUBS';
export const FETCH_BOOKCLUBS_SUCCESS = 'FETCH_BOOKCLUBS_SUCCESS';
export const FETCH_BOOKCLUBS_FAILURE = 'FETCH_BOOKCLUBS_FAILURE';

export const SUBMIT_CONTACT_US = 'SUBMIT_CONTACT_US';
export const SUBMIT_CONTACT_US_SUCCESS = 'SUBMIT_CONTACT_US_SUCCESS';
export const SUBMIT_CONTACT_US_FAILURE = 'SUBMIT_CONTACT_US_FAILURE';

export const SUBMIT_JOIN_US = 'SUBMIT_JOIN_US';
export const SUBMIT_JOIN_US_SUCCESS = 'SUBMIT_JOIN_US_SUCCESS';
export const SUBMIT_JOIN_US_FAILURE = 'SUBMIT_JOIN_US_FAILURE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const FETCH_USER_CART = 'FETCH_USER_CART';
export const FETCH_USER_CART_SUCCESS = 'FETCH_USER_CART_SUCCESS';
export const FETCH_USER_CART_FAILURE = 'FETCH_USER_CART_FAILURE';

export const SEARCH_BOOKS = 'SEARCH_BOOKS';
export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';
export const SEARCH_BOOKS_FAILURE = 'SEARCH_BOOKS_FAILURE';

export const CART_SUCCESS = 'CART_SUCCESS';
export const CART_FAILURE = 'CART_FAILURE';

export const ADD_ADDRESS_SAGA = 'ADD_ADDRESS_SAGA';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAILURE = 'ADD_ADDRESS_FAILURE';

export const FETCH_ADDRESS = 'FETCH_ADDRESS';
export const FETCH_ADDRESS_SUCCESS = 'FETCH_ADDRESS_SUCCESS';
export const FETCH_ADDRESS_FAILURE = 'FETCH_ADDRESS_FAILURE';

export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';

export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';

export const FETCH_SITE_DETAILS = 'FETCH_SITE_DETAILS';
export const FETCH_SITE_DETAILS_SUCCESS = 'FETCH_SITE_DETAILS_SUCCESS';
export const FETCH_SITE_DETAILS_FAILURE = 'FETCH_SITE_DETAILS_FAILURE';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const UPDATE_FAVOURITE = 'UPDATE_FAVOURITE';
export const UPDATE_FAVOURITE_SUCCESS = 'UPDATE_FAVOURITE_SUCCESS';
export const UPDATE_FAVOURITE_FAILURE = 'UPDATE_FAVOURITE_FAILURE';

export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const POST_TO_FAVOURITE_SUCCESS = 'POST_TO_FAVOURITE_SUCCESS';
export const POST_TO_FAVOURITE_FAILURE = 'POST_TO_FAVOURITE_FAILURE';

export const FETCH_USER_FAVOURITE = 'FETCH_USER_FAVOURITE';
export const FETCH_USER_FAVOURITE_SUCCESS = 'FETCH_USER_FAVOURITE_SUCCESS';
export const FETCH_USER_FAVOURITE_FAILURE = 'FETCH_USER_FAVOURITE_FAILURE';

export const START_ACTION = 'START_ACTION';
export const STOP_ACTION = 'STOP_ACTION';
export const REFRESH_ACTION_START = 'REFRESH_ACTION_START';
export const REFRESH_ACTION_STOP = 'REFRESH_ACTION_STOP';

export const FETCH_ORDER = 'FETCH_ORDER';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';

export const NETWORK_ERROR = 'NETWORK_ERROR';
export const NETWORK_INACTIVE = 'NETWORK_INACTIVE';
export const NETWORK_ACTIVE = 'NETWORK_ACTIVE';

export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS';
export const FETCH_CURRENCIES_FAILURE = 'FETCH_CURRENCIES_FAILURE';

export const DO_PAYMENT = 'DO_PAYMENT';

export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const SET_FCM_TOKEN = 'SET_FCM_TOKEN';
export const SET_FCM_TOKEN_SUCCESS = 'SET_FCM_TOKEN_SUCCESS';
export const SET_FCM_TOKEN_FAILURE = 'SET_FCM_TOKEN_FAILURE';


export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE';


export const SWITCH_CURRENCY = 'SWITCH_CURRENCY';
export const SWITCH_CURRENCY_SUCCESS = 'SWITCH_CURRENCY_SUCCESS';
export const SWITCH_CURRENCY_FAILURE = 'SWITCH_CURRENCY_FAILURE';




export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const EDIT_ADDRESS_SUCCESS = 'EDIT_ADDRESS_SUCCESS';
export const EDIT_ADDRESS_FAILURE = 'EDIT_ADDRESS_FAILURE';


export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAILURE = 'DELETE_ADDRESS_FAILURE';

export const FETCH_BANNER = 'FETCH_BANNER';
export const FETCH_BANNER_SUCCESS = 'FETCH_BANNER_SUCCESS';
export const FETCH_BANNER_FAILURE = 'FETCH_BANNER_FAILURE';



export const FETCH_STATIC = 'FETCH_STATIC';
export const FETCH_STATIC_SUCCESS = 'FETCH_STATIC_SUCCESS';
export const FETCH_STATIC_FAILURE = 'FETCH_STATIC_FAILURE';



export const PUSH_NOTIFICATION_FUNCTION = 'PUSH_NOTIFICATION_FUNCTION';
export const PUSH_NOTIFICATION_FUNCTION_SUCCESS = 'PUSH_NOTIFICATION_FUNCTION_SUCCESS';
export const PUSH_NOTIFICATION_FUNCTION_FAILURE = 'PUSH_NOTIFICATION_FUNCTION_FAILURE';


export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';





// somthing to be removed later 
export const UPDATE_CART_ITEM_ORDER_COMPLETE = 'UPDATE_CART_ITEM_ORDER_COMPLETE';






export const RE_ADD_TO_CART = 'RE_ADD_TO_CART';
export const RE_ADD_TO_CART_SUCCESS = 'RE_ADD_TO_CART_SUCCESS';
export const RE_ADD_TO_CART_FAILURE = 'RE_ADD_TO_CART_FAILURE';


export const UPDATE_CART_PRICES = 'UPDATE_CART_PRICES';
export const UPDATE_CART_PRICES_SUCCESS = 'UPDATE_CART_PRICES_SUCCESS';
export const UPDATE_CART_PRICES_FAILURE = 'UPDATE_CART_PRICES_FAILURE';





export const UPDATE_CART_PRICES_OFFLINE = 'UPDATE_CART_PRICES_OFFLINE';
export const UPDATE_CART_PRICES_OFFLINE_SUCCESS = 'UPDATE_CART_PRICES_OFFLINE_SUCCESS';
export const UPDATE_CART_PRICES_OFFLINE_FAILURE = 'UPDATE_CART_PRICES_OFFLINE_FAILURE';






export const FETCH_GENRE = 'FETCH_GENRE';
export const FETCH_GENRE_SUCCESS = 'FETCH_GENRE_SUCCESS';
export const FETCH_GENRE_FAILURE = 'FETCH_GENRE_FAILURE';



export const GUESTUSER_TOKEN = 'GUESTUSER_TOKEN';
export const GUESTUSER_TOKEN_SUCCESS = 'GUESTUSER_TOKEN_SUCCESS';
export const GUESTUSER_TOKEN_FAILURE = 'GUESTUSER_TOKEN_FAILURE';