export const SPLASH_ACTION = 'SPLASH_ACTION';
export const SPLASH_COMPLETE = 'SPLASH_COMPLETE';

export const SWITCH_LANG = 'SWITCH_LANG';
export const SWITCH_LANG_SUCCESS = 'SWITCH_LANG_SUCCESS';
export const SWITCH_LANG_FAILURE = 'SWITCH_LANG_FAILURE';

export const FETCH_AD = 'FETCH_AD';
export const FETCH_AD_SUCCESS = 'FETCH_AD_SUCCESS';
export const FETCH_AD_FAILURE = 'FETCH_AD_FAILURE';

export const SKIP_AD = 'SKIP_AD';
export const SKIP_AD_SUCCESS = 'SKIP_AD_SUCCESS';
export const SKIP_AD_FAILURE = 'SKIP_AD_FAILURE';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const REQUEST_BOOK = 'REQUEST_BOOK';
export const REQUEST_BOOK_SUCCESS = 'REQUEST_BOOK_SUCCESS';
export const REQUEST_BOOK_FAILURE = 'REQUEST_BOOK_FAILURE';

export const FETCH_BOOK_LISTS = 'FETCH_BOOK_LISTS';
export const FETCH_BOOK_LISTS_SUCCESS = 'FETCH_BOOK_LISTS_SUCCESS';
export const FETCH_BOOK_LISTS_FAILURE = 'FETCH_BOOK_LISTS_FAILURE';

export const FETCH_ENGLISH_BOOKS = 'FETCH_ENGLISH_BOOKS';
export const FETCH_ENGLISH_BOOKS_SUCCESS = 'FETCH_ENGLISH_BOOKS_SUCCESS';
export const FETCH_ENGLISH_BOOKS_FAILURE = 'FETCH_ENGLISH_BOOKS_FAILURE';

export const FETCH_ARABIC_BOOKS = 'FETCH_ARABIC_BOOKS';
export const FETCH_ARABIC_BOOKS_SUCCESS = 'FETCH_ARABIC_BOOKS_SUCCESS';
export const FETCH_ARABIC_BOOKS_FAILURE = 'FETCH_ARABIC_BOOKS_FAILURE';

export const FETCH_RELATED_BOOKS = 'FETCH_RELATED_BOOKS';
export const FETCH_RELATED_BOOKS_SUCCESS = 'FETCH_RELATED_BOOKS_SUCCESS';
export const FETCH_RELATED_BOOKS_FAILURE = 'FETCH_RELATED_BOOKS_FAILURE';

export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const FETCH_BOOKMARKS_SUCCESS = 'FETCH_BOOKMARKS_SUCCESS';
export const FETCH_BOOKMARKS_FAILURE = 'FETCH_BOOKMARKS_FAILURE';

export const FETCH_BOOKCLUBS = 'FETCH_BOOKCLUBS';
export const FETCH_BOOKCLUBS_SUCCESS = 'FETCH_BOOKCLUBS_SUCCESS';
export const FETCH_BOOKCLUBS_FAILURE = 'FETCH_BOOKCLUBS_FAILURE';
